const data = [
  { title: '패턴', pageNumber: 1 },
  { title: '마음가짐', pageNumber: 2 },
  { title: 'HTML 기초', pageNumber: 3 },
  { title: 'css 기초', pageNumber: 4 },
  { title: 'CSSflex', pageNumber: 5 },
  { title: 'Mac 계산기 클론하기', pageNumber: 6 },
  { title: 'CSS grid', pageNumber: 7 },
  { title: 'slice? splice', pageNumber: 8 },
  { title: '함수를 정의하는 방법', pageNumber: 9 },
  { title: '순열(Permutation) 구현하기', pageNumber: 10 },
  { title: '문자열에서 특정 위치의 문자를 변경하고 싶은 경우', pageNumber: 11 },
  { title: 'letIt const', pageNumber: 12 },
  { title: 'nvm', pageNumber: 13 },
  { title: '요소 노드의 텍스트 조작하기(nodeValue, textContent, innerHTML)', pageNumber: 14 },
  { title: '자바스크립트의 배열은 배열이 아니다!', pageNumber: 15 },
  { title: 'JSON 다루기(JSON.parse), JSON.stringify())', pageNumber: 16 },
  { title: '원시 자료형과 참조 자료형', pageNumber: 17 },
  { title: '[]===[]는 왜 false인가', pageNumber: 18 },
  { title: 'this (동적 바인딩)', pageNumber: 19 },
  { title: '유효성 검사를 포함한 간단한 회원가입 폼 페이지 만들기', pageNumber: 20 },
  { title: '#fff와 #ffffff', pageNumber: 21 },
  { title: '안다고 생각했지만, 헷갈렸던 문법들', pageNumber: 22 },
  { title: 'DOM이 뭔가요?', pageNumber: 23 },
  { title: '영화 좌석 예약 페이지 만들기 ', pageNumber: 24 },
  { title: '테두리가 두 줄처럼 보이는 경우 (border)', pageNumber: 25 },
  { title: '패턴', pageNumber: 26 },
  { title: '마음가짐', pageNumber: 27 },
  { title: 'HTML 기초', pageNumber: 28 },
  { title: 'css 기초', pageNumber: 29 },
  { title: 'css 기초', pageNumber: 30 },
  { title: 'Mac 계산기 클론하기', pageNumber: 31 },
  { title: 'CSS grid', pageNumber: 32 },
  { title: 'slice? splice', pageNumber: 33 },
  { title: '함수를 정의하는 방법', pageNumber: 34 },
  { title: '순열(Permutation) 구현하기', pageNumber: 35 },
  { title: '문자열에서 특정 위치의 문자를 변경하고 싶은 경우', pageNumber: 36 },
  { title: 'letIt const', pageNumber: 37 },
  { title: 'nvm', pageNumber: 38 },
  { title: '요소 노드의 텍스트 조작하기(nodeValue, textContent, innerHTML)', pageNumber: 39 },
  { title: '자바스크립트의 배열은 배열이 아니다!', pageNumber: 40 },
  { title: 'JSON 다루기(JSON.parse), JSON.stringify())', pageNumber: 41 },
  { title: '원시 자료형과 참조 자료형', pageNumber: 42 },
  { title: '[]===[]는 왜 false인가', pageNumber: 43 },
  { title: 'this (동적 바인딩)', pageNumber: 44 },
  { title: '유효성 검사를 포함한 간단한 회원가입 폼 페이지 만들기', pageNumber: 45 },
  { title: '#fff와 #ffffff', pageNumber: 46 },
  { title: '안다고 생각했지만, 헷갈렸던 문법들', pageNumber: 47 },
  { title: 'DOM이 뭔가요?', pageNumber: 48 },
  { title: '영화 좌석 예약 페이지 만들기 ', pageNumber: 49 },
  { title: '테두리가 두 줄처럼 보이는 경우 (border)', pageNumber: 50 }
];